### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by fpemud** [sonyxperiadev/device-sony-suzuran#19]
Is there any detailed project status, such as what works and what doesn't?
Additionally, is there any road map or TODO list for this project?

**Comment by fpemud** [comment]
Can you give some explanation or hint, instead of closing it without any word?

**Comment by jerpelea** [comment]
There is no project status yet,i have noted your request and we will try to publish a page with the status
Most of the hw works and we all work on adding more and more features
