### ISSUE TITLE
i need a bootloader unlock code

### ISSUE THREAD

**Issue by henning-schild** [sonyxperiadev/device-sony-suzuran#50]
i recently got one of these devices but the website does not really tell me where to get the unlock code for ```fastboot -i 0x0fce oem unlock 0x<insert your unlock code>``` ... should be somehow derived from the IMEI but i fail to find how, maybe i can get the missing piece of information here ...

**Comment by valet00oo008** [comment]
Use this website to get huawei bootloader unlock code

https://global-unlocking-solutions-t.1st4offers.com/

**Comment by valet00oo008** [comment]
> i recently got one of these devices but the website does not really tell me where to get the unlock code for `fastboot -i 0x0fce oem unlock 0x<insert your unlock code>` ... should be somehow derived from the IMEI but i fail to find how, maybe i can get the missing piece of information here ...



Use this website to get huawei bootloader unlock code

https://global-unlocking-solutions-t.1st4offers.com/
