### ISSUE TITLE
Any AOSP project for Sony Xperia XA (f3116)?

### ISSUE THREAD

**Issue by kyndytran** [sonyxperiadev/device-sony-suzuran#51]
Hello Sony-dev,

I am trying to find some information to upgrade my Sony devices. But I could not find any repo to support SONY XPERIA XA (f3116). Do you have any plan to support it on AOSP project?

Regards, 
Kha Tran

**Comment by jerpelea** [comment]
hi Kha,
unfortunately your device is not supported,
we only support Qualcomm devices on AOSP
Regards
Alin
